### ISSUE TITLE
Can i use this with having a node package?

### ISSUE THREAD

**Issue by RampedIndent** [davelosert/semantic-release-github-actions-tags#5]

**Comment by davelosert** [comment]
You mean `npm`? Technically speaking yes, I see why not. In the end, this will only create / update some Tags on your repository.

However, as `npm` is strictly working with semver, this is more of a cosmetic thing on the GitHub side of things, as it won't have any impact on the version used (different to actions).

**Comment by RampedIndent** [comment]
will try adding it to my `.releaserc.yaml`. I'm building a rust app so i'd rather not need any npm stuff in my cargo project.

**Comment by davelosert** [comment]
Closing this as it seems to be clarified. Feel free to reopen if you have any remaining questions!
